// Pulls SIP accounts from TalkPilot and keeps local Asterisk registered on them.
// - GET /api/asterisk/sip-accounts  (X-Asterisk-Token)
// - Writes /etc/asterisk/pjsip_accounts.conf with a registration + endpoint per account
// - Runs `asterisk -rx "pjsip reload"` ONLY when the file actually changed
const axios = require('axios');
const { exec } = require('child_process');
const { promisify } = require('util');
const execAsync = promisify(exec);
const fs = require('fs');

const PJSIP_FILE = '/etc/asterisk/pjsip_accounts.conf';

function sanitizeServer(server) {
  let s = String(server || '').trim();
  if (!s) return null;
  if (!/:\/\//.test(s)) s = 'sip:' + s;
  return s.replace(/^\w+:/, p => p.toLowerCase()); // normalize uri scheme prefix
}

function hostOnly(server) {
  const uri = sanitizeServer(server) || '';
  try {
    const u = new URL(uri.replace(/^\w+:/, 'http://'));
    return u.hostname;
  } catch { return null; }
}

function portOf(server) {
  const uri = sanitizeServer(server) || '';
  // strip the scheme (e.g. "sip:") first so the scheme colon is never
  // mistaken for a port separator
  const bare = uri.replace(/^[a-zA-Z]+:/, '');
  const m = bare.match(/:(\d+)/);
  return m ? m[1] : '5060';
}

// Always-AI numbers are the ONLY ones Asterisk keeps registered with the
// provider. Manual numbers are registered by the desktop app directly; if we
// also register them here the provider forks each inbound call to both and
// cancels the desktop leg the moment the manual Dial branch fails.
function isAiMode(a) {
  if (a && a.mode) return String(a.mode).toLowerCase() === 'ai';
  return !!(a && a.ai_mode);
}

function genConfig(accounts) {
  const safe = s => String(s || '').replace(/[^a-zA-Z0-9._-]/g, '');
  let out = '; AUTO-GENERATED by ai-call-asterisk — DO NOT EDIT\n';
  let used = new Set();
  for (const a of accounts) {
    const host = hostOnly(a.sip_server);
    if (!host || !a.sip_number || !a.sip_password) continue;
    const aiInbound = isAiMode(a);
    const aiOutbound = !!(a.outbound_enabled);
    if (!aiInbound && !aiOutbound) {
      console.log(`[sip-sync] skipping ${a.sip_number} — AI inbound off & outbound disabled`);
      continue;
    }
    const tag = safe(a.sip_number) + '_' + Math.abs(a.id || 0);
    if (used.has(tag)) continue; used.add(tag);

    // AI inbound numbers also register with the provider so incoming calls
    // reach Asterisk. Outbound-only numbers get the endpoint WITHOUT the
    // registration — the desktop keeps owning incoming, no forked contact.
    if (aiInbound) {
      out += `\n; --- ${a.shop_name || a.sip_number} (AI inbound) ---\n`;
      out += `[r_${tag}]\ntype=registration\ntransport=transport-udp\noutbound_auth=ra_${tag}\nserver_uri=sip:${host}:${portOf(a.sip_server)}\ncontact_user=${safe(a.sip_number)}\nclient_uri=sip:${safe(a.sip_number)}@${host}\nretry_interval=15\nforbidden_retry_interval=15\nexpiration=180\n\n`;
    } else {
      out += `\n; --- ${a.shop_name || a.sip_number} (AI outbound only) ---\n`;
    }
    out += `[ra_${tag}]\ntype=auth\nauth_type=userpass\nrealm=${host}\nusername=${safe(a.sip_number)}\npassword=${String(a.sip_password).replace(/\n/g, '')}\n\n`;
    out += `[e_${tag}]\ntype=endpoint\ncontext=from-trunk\ntransport=transport-udp\ndisallow=all\nallow=ulaw\noutbound_auth=ra_${tag}\naors=ao_${tag}\nfrom_domain=${host}\ndirect_media=no\nrtp_symmetric=yes\nforce_rport=yes\nrewrite_contact=yes\nice_support=no\ndtmf_mode=rfc4733\n\n`;
    out += `[ao_${tag}]\ntype=aor\ncontact=sip:${host}:${portOf(a.sip_server)}\nmax_contacts=2\nqualify_frequency=60\n\n`;
    if (aiInbound) {
      out += `[id_${tag}]\ntype=identify\nendpoint=e_${tag}\nmatch=${host}\n`;
    }
  }
  return out;
}

function reloadAsterisk() {
  return execAsync(`asterisk -rx 'pjsip reload'`).catch(e => console.error('[sip-sync] reload failed:', e.message));
}

function parseRegNames(cfg) {
  const names = [];
  const re = /\[(r_[^\]]+)\]/g;
  let m;
  while ((m = re.exec(cfg || '')) !== null) names.push(m[1]);
  return names;
}

function unregisterAsterisk(reg) {
  return execAsync(`asterisk -rx 'pjsip send unregister ${reg}'`).then(() => {
    console.log(`[sip-sync] unregistered ${reg} (no longer AI)`);
  }).catch(e => console.error(`[sip-sync] unregister ${reg} failed:`, e.message));
}

async function syncOnce(env) {
  let prev = null;
  try { prev = fs.readFileSync(PJSIP_FILE, 'utf8'); } catch {}
  const prevNames = parseRegNames(prev);

  let list = null;
  let cfg = null;
  try {
    const { data } = await axios.get(`${env.LARAVEL_BASE}/api/asterisk/sip-accounts`, {
      headers: { 'X-Asterisk-Token': env.LARAVEL_TOKEN },
      timeout: 10000,
    });
    list = Array.isArray(data) ? data : (data.data || []);
    cfg = genConfig(list);
  } catch (e) {
    // Portal unreachable. Fail SAFE to human agents: never keep a stale AI
    // registration alive — a leftover contact made the provider fork every
    // call to both the AI node and the desktop and cancel the desktop leg
    // within ~1s. Unregister everything until the portal is reachable again.
    console.error('[sip-sync] portal unreachable:', e.message);
    return Promise.all([
      execAsync(`asterisk -rx 'pjsip send unregister *all'`).then(() => {
        console.log('[sip-sync] portal down — unregistered all auto registrations (fail-safe to manual/human)');
      }).catch(e => console.error('[sip-sync] unregister *all failed:', e.message)),
    ]).then(() => null);
  }

  if (prev !== cfg) {
    // needs root to write; app is expected to run as root in WSL
    fs.writeFileSync(PJSIP_FILE, cfg);
    // Dropping an AI registration needs an ACTIVE unregister — a pjsip reload
    // alone leaves the old binding on the provider, which keeps forking calls.
    const newNames = parseRegNames(cfg);
    const dropped = prevNames.filter(n => !newNames.includes(n));
    if (dropped.length > 0) {
      console.log(`[sip-sync] unregistering dropped AI registrations: ${dropped.join(', ')}`);
      await Promise.all(dropped.map(unregisterAsterisk));
    }
    console.log(`[sip-sync] ${newNames.length} of ${list.length} account(s) AI-enabled; written to ${PJSIP_FILE} — reloading`);
    await reloadAsterisk();
  }
  return list;
}

function startSync(env, intervalMs = 60000) {
  return setInterval(() => syncOnce(env).catch(e => console.error('[sip-sync] error:', e.message)), intervalMs);
}

module.exports = { syncOnce, startSync, genConfig };
